CREATE OR REPLACE STREAM "DISTINATION_SQL_STREAM"(
ticker_symbol VARCHAR(4),
count_price DOUBLE
);

CREATE OR REPLACE PUMP "STREAM_PUMP" AS 
INSERT INTO "DISTINATION_SQL_STREAM"
SELECT STREAM
ticker_symbol
,count(price) as count_price
from
"SOURCE_SQL_STREAM_001"
GROUP BY
    ticker_symbol,STEP("SOURCE_SQL_STREAM_001".ROWTIME BY INTERVAL '15' SECOND);